version: '3.8'

services:
  flowise:
      image: flowiseai/flowise
      restart: always
      depends_on:
        - ollama
        - redis
      environment:
          - PORT=${FLOWISE_PORT}
          - FLOWISE_USERNAME=${FLOWISE_USERNAME}
          - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
          - DATABASE_PATH=/root/.flowise
          - APIKEY_PATH=/root/.flowise
          - LOG_PATH=/root/.flowise/logs
          - SECRETKEY_PATH=/root/.flowise
          - BLOB_STORAGE_PATH=/root/.flowise/storage
      volumes:
          - "./flowise_data:/root/.flowise:z"
      ports:
          - '${FLOWISE_PORT}:${FLOWISE_PORT}'
      command: /bin/sh -c "sleep 3; flowise start"

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    restart: always
    volumes:
      - "./ollama_data:/root/.ollama:z"
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./redis_data:/data:z"
